NiRi3
svelamuri26/NiRi pull request #6
Opened 2024-01-18 07:47 UTC by svelamuri26

2024-01-21 22:26 UTC, MenilV commented
Let's please add Jira ticket number in the commit messages in the following format:

"NIRI-27 Add Cart Item module"

2024-01-22 18:12 UTC, MenilV requested changes
A few things to check but overall good.

2024-01-22 18:12 UTC, MenilV commented on src/main/java/com/example/NiRi/SwaggerConfig.java
do we need this? is this the file causing issues?

2024-01-22 18:12 UTC, MenilV commented on src/main/java/com/example/NiRi/modules/User.java
> +>>>>>>> origin/main
this is a conflict, please resolve it.

2024-01-22 19:59 UTC, svelamuri26 commented on src/main/java/com/example/NiRi/SwaggerConfig.java
I just forgot to delete it. I did it now.

2024-01-22 19:59 UTC, svelamuri26 commented on src/main/java/com/example/NiRi/modules/User.java
> +>>>>>>> origin/main
resolved and pushed again.

2024-01-22 20:03 UTC, svelamuri26 commented
Thank you for the feedback.

2024-01-23 09:29 UTC, MenilV approved these changes

2024-01-23 10:39 UTC, merged